### ISSUE TITLE
ConcurrentModificationException while caching

### ISSUE THREAD

**Issue by MaxWainer** [yakovliam-com/spacechat#23]
Sometimes, plugin throws next error:

```
[13:39:53 WARN]: [dev.spaceseries.spacechat.lib.caffeine.cache.LocalAsyncCache] Exception thrown during asynchronous load
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at dev.spaceseries.spacechat.lib.configurate.ListConfigValue.unwrapped(ListConfigValue.java:95) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.childrenList(AbstractConfigurationNode.java:423) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:54) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.ConfigurationNode.getList(ConfigurationNode.java:705) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.storage.impl.json.JsonStorage.getUser(JsonStorage.java:86) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.user.UserManager.lambda$new$0(UserManager.java:32) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:104) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 6 more
```
and
```
[13:41:40 WARN]: [dev.spaceseries.spacechat.lib.caffeine.cache.LocalAsyncCache] Exception thrown during asynchronous load
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Index: 13785, Size: 0
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 13785, Size: 0
        at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:481) ~[?:?]
        at dev.spaceseries.spacechat.lib.configurate.ListConfigValue.putChildInternal(ListConfigValue.java:178) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.ListConfigValue.putChildInternal(ListConfigValue.java:149) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.ListConfigValue.putChildIfAbsent(ListConfigValue.java:133) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.attachChild(AbstractConfigurationNode.java:610) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.attachChildIfAbsent(AbstractConfigurationNode.java:551) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.parentEnsureAttached(AbstractConfigurationNode.java:536) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.attachIfNecessary(AbstractConfigurationNode.java:543) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.insertNewValue(AbstractConfigurationNode.java:239) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.raw(AbstractConfigurationNode.java:340) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.raw(AbstractConfigurationNode.java:43) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.serialize.AbstractListChildSerializer.serialize(AbstractListChildSerializer.java:85) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.ScopedConfigurationNode.set(ScopedConfigurationNode.java:110) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.ScopedConfigurationNode.set(ScopedConfigurationNode.java:40) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.storeDefault(AbstractConfigurationNode.java:118) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:135) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.ConfigurationNode.getList(ConfigurationNode.java:705) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.storage.impl.json.serializer.UserConfigurateSerializer.deserialize(UserConfigurateSerializer.java:61) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.storage.impl.json.serializer.UserConfigurateSerializer.deserialize(UserConfigurateSerializer.java:20) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:58) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.configurate.ConfigurationNode.getList(ConfigurationNode.java:705) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.storage.impl.json.JsonStorage.getUser(JsonStorage.java:86) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.user.UserManager.lambda$new$0(UserManager.java:32) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at dev.spaceseries.spacechat.lib.caffeine.cache.CacheLoader.lambda$asyncLoad$0(CacheLoader.java:104) ~[SpaceChat-2.3.3-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 6 more
```

Plugin version:
```
> bukkit:ver SpaceChat
[13:43:06 INFO]: SpaceChat version 2.3.3-SNAPSHOT
[13:43:06 INFO]: Simple and effective chat formatting
[13:43:06 INFO]: Website: https://www.spaceseries.dev/
[13:43:06 INFO]: Author: yakovliam
```

Server version:
```
> ver
[13:43:41 INFO]: Checking version, please wait...
[13:43:41 INFO]: This server is running Purpur version git-Purpur-1393 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3ff85ed on ver/1.17.1)
[13:43:41 INFO]: You are running the latest version
[13:43:41 INFO]: Previous version: git-Purpur-1385 (MC: 1.17.1)
```

Steps to reproduce:
- Started thorwing this error, when on server, more than ~50 players

**Comment by yakovliam** [comment]
Thanks for the report, I'll look into this ASAP. In the meantime, would you mind contacting me on discord so I can issue you a refund?

**Comment by conclube** [comment]
@MaxWainer in case if this issue still occurs, can you send the configurations you used to produce the error?
